---
- name: Update apt cache
  become: true
  apt: update_cache=true cache_valid_time=3600
  when: |
    asdf_nodejs is defined
    or asdf_erlang is defined
    or asdf_elixir is defined
    or asdf_postgres is defined

- name: Checkout ASDF core
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '{{ asdf_user_home }}/.asdf'
    version: v0.8.0
