---
- name: Update apt cache
  become: true
  ansible.builtin.apt: update_cache=true cache_valid_time=3600
  when: |
    asdf_nodejs is defined
    or asdf_erlang is defined
    or asdf_elixir is defined
    or asdf_postgres is defined
    or asdf_golang is defined
