---
- name: Install unzip
  become: true
  ansible.builtin.apt: pkg=unzip state=present

- name: Install elixir plugin and desired elixir versions
  become: true
  become_user: '{{ asdf_user }}'
  block:
  - name: Install elixir asdf plugin
    ansible.builtin.command: "{{ asdf_binary }} plugin add elixir"
    when: "'elixir' not in installed_asdf_plugins"

  - name: Get list of installed elixir versions
    ansible.builtin.command: '{{ asdf_binary }} list elixir'
    register: asdf_installed_elixir_versions
    changed_when: false
    check_mode: false

  - name: Install elixir versions
    ansible.builtin.command: "{{ asdf_binary }} install elixir {{ item }}"
    when: item not in asdf_installed_elixir_versions.stdout_lines | map('trim')
    with_items: '{{ asdf_elixir }}'
