---
- name: Ensure the user is set
  ansible.builtin.fail: msg="Please set the 'asdf_user' variable"
  when: asdf_user is not defined

- name: Get information on the asdf user
  ansible.builtin.user:
    name: '{{ asdf_user }}'
    state: present
  register: asdf_user_registered

- name: Set the asdf user home for future use
  ansible.builtin.set_fact:
    asdf_user_home: '{{ asdf_user_registered.home }}'
    asdf_binary: 'asdf'

- import_tasks: dependencies.yml

- import_tasks: asdf_plugins.yml
  become: true
  become_user: '{{ asdf_user }}'
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'

- import_tasks: nodejs.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_nodejs is defined

- import_tasks: yarn.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_yarn is defined

- import_tasks: erlang.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_erlang is defined

- import_tasks: elixir.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_elixir is defined

- import_tasks: ruby.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_ruby is defined

- import_tasks: golang.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_golang is defined


- import_tasks: postgres.yml
  environment:
    PATH: '{{ asdf_user_home }}/.asdf/bin:{{ ansible_env.PATH }}'
  when: asdf_postgres is defined
