---
- name: Ensure the user is set
  fail: msg="Please set the 'asdf_user' variable"
  when: asdf_user is not defined

- name: Get information on the asdf user
  user:
    name: '{{ asdf_user }}'
    state: present
  register: asdf_user_registered

- name: Set the asdf user home for future use
  set_fact:
    asdf_user_home: '{{ asdf_user_registered.home }}'
    asdf_binary: '{{ asdf_user_registered.home }}/.asdf/bin/asdf'

- import_tasks: asdf_plugins.yml
