---
- name: Install curl
  become: true
  ansible.builtin.apt: pkg=curl state=present

- name: Install node plugin and desired node versions
  become: true
  become_user: '{{ asdf_user }}'
  block:
  - name: Install asdf nodejs plugin
    ansible.builtin.command: "{{ asdf_binary }} plugin add nodejs"
    when: "'nodejs' not in installed_asdf_plugins"

  - name: Get list of installed nodejs versions
    ansible.builtin.command: '{{ asdf_binary }} list nodejs'
    register: asdf_installed_nodejs_versions
    changed_when: false
    check_mode: false

  - name: Install nodejs versions
    ansible.builtin.command: "{{ asdf_binary }} install nodejs {{ item }}"
    when: item not in asdf_installed_nodejs_versions.stdout_lines | map('trim')
    with_items: '{{ asdf_nodejs }}'
