---
- name: Install ruby dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - autoconf
      - bison
      - build-essential
      - libdb-dev
      - libffi-dev
      - libgdbm-dev
      - libgdbm6
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
    state: present

- name: Install ruby plugin and desired ruby versions
  become: true
  become_user: '{{ asdf_user }}'
  block:
    - name: Install ruby asdf plugin
      ansible.builtin.command: "{{ asdf_binary }} plugin add ruby"
      when: "'ruby' not in installed_asdf_plugins"

    - name: Get list of installed ruby versions
      ansible.builtin.command: '{{ asdf_binary }} list ruby'
      register: asdf_installed_ruby_versions
      changed_when: false
      check_mode: false

    - name: Install ruby versions
      ansible.builtin.command: "{{ asdf_binary }} install ruby {{ item }}"
      when: item not in asdf_installed_ruby_versions.stdout_lines | map('trim')
      with_items: '{{ asdf_ruby }}'
