---
- name: Install yarn asdf plugin
  command: "{{ asdf_binary }} plugin add yarn"
  when: "'yarn' not in installed_asdf_plugins"

- name: Get list of installed yarn versions
  command: '{{ asdf_binary }} list yarn'
  register: asdf_installed_yarn_versions
  changed_when: false
  check_mode: false

- name: Install yarn versions
  command: "{{ asdf_binary }} install yarn {{ item }}"
  when: item not in asdf_installed_yarn_versions.stdout_lines | map('trim')
  with_items: '{{ asdf_yarn }}'
