---
- name: Converge
  hosts: all

  vars:
    asdf_user: root
    asdf_nodejs:
      - 12.16.1
      - 13.14.0
    asdf_yarn:
      - 1.22.5
    asdf_elixir:
      - 1.14.0-otp-25
    asdf_erlang:
      - 25.0.4
    asdf_ruby:
      - 3.0.1

  tasks:
    - name: "Include ansible-galaxy-asdf"
      ansible.builtin.include_role:
        name: "ansible-galaxy-asdf"
