---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_bullseye
    image: debian:bullseye
    dockerfile: Dockerfile
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint -c .ansible-lint
