---
- name: Verify
  hosts: all
  gather_facts: false

  vars:
    expected_asdf_packages: [
      "elixir",
      "  1.14.0-otp-25",
      "erlang",
      "  25.0.4",
      "nodejs",
      "  12.16.1",
      "  13.14.0",
      "yarn",
      "  1.22.5"
    ]

  tasks:
    - name: List which plugins are installed
      ansible.builtin.command: "/root/.asdf/bin/asdf plugin list"
      register: asdf_plugin_list
      changed_when: false

    - name: Get the asdf fish completions
      ansible.builtin.stat:
        path: "/root/.config/fish/completions/asdf.fish"
      register: fish_asdf_completions
      changed_when: false

    - name: Ensure the fish asdf completions are installed
      ansible.builtin.assert:
        that: fish_asdf_completions.stat.exists

    - name: Get the versions of all packages installed
      ansible.builtin.command: "/root/.asdf/bin/asdf list"
      register: installed_asdf_packages
      changed_when: false

    - name: Ensure that everything is installed
      ansible.builtin.assert:
        that: '{{ installed_asdf_packages.stdout_lines }} == {{ expected_asdf_packages }}'
